const STATUSES=["New","Confirmed","Flowers Ready","Arranging","Wrapping","Ready","Out for Delivery","Delivered"];
const STORAGE_KEY="serendib_orders_preview";
let selectedStatus="All",editingId=null,currentId=null,reportMode="month";

function toLocalInput(d){const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}
function localDateInput(d=new Date()){const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)}
function getOrders(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return[];try{return JSON.parse(raw)}catch{return[]}}
function setOrders(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function money(v){return Number(v||0).toLocaleString()}
function formatDate(v){if(!v)return"";return new Date(v).toLocaleString([], {year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}
function isToday(v){if(!v)return false;const d=new Date(v),n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}
function currentMonthValue(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function monthLabel(v){if(!v)return"All Time";const [y,m]=v.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString([], {month:"long",year:"numeric"})}
function n(v){return Math.max(Number(v||0),0)}
function orderBouquetValue(o){return n(o.amount)}
function orderDeliveryFee(o){return n(o.deliveryFee)}
function orderTotal(o){return orderBouquetValue(o)+orderDeliveryFee(o)}
function orderPayments(o){if(Array.isArray(o.payments))return o.payments;const a=n(o.advanceAmount);if(a>0)return [{id:"legacy-"+o.id,amount:a,date:o.createdAt||new Date().toISOString(),note:"Advance"}];if(o.paymentStatus==="Paid"&&orderTotal(o)>0)return [{id:"legacy-paid-"+o.id,amount:orderTotal(o),date:o.createdAt||new Date().toISOString(),note:"Paid"}];return []}
function orderPaid(o){return Math.min(orderPayments(o).reduce((s,p)=>s+n(p.amount),0),orderTotal(o))}
function orderDue(o){return Math.max(orderTotal(o)-orderPaid(o),0)}
function orderCosts(o){return n(o.flowerCost)+n(o.wrappingCost)+n(o.deliveryCost)+n(o.otherCost)}
function orderProfit(o){return orderTotal(o)-orderCosts(o)}
function paymentStatus(o){if(orderTotal(o)<=0)return"Unpaid";if(orderDue(o)<=0)return"Paid";return orderPaid(o)>0?"Deposit Paid":"Unpaid"}
function sanitizePhone(phone){let p=String(phone||"").replace(/\D/g,"");if(p.startsWith("0"))p="94"+p.slice(1);return p}
function waLink(phone,text){const p=sanitizePhone(phone);return p?`https://wa.me/${p}?text=${encodeURIComponent(text)}`:"#"}
function nextOrderNumber(){const nums=getOrders().map(o=>parseInt((o.orderNumber||"").replace(/\D/g,""))||0);return"SP-"+String((Math.max(0,...nums)+1)).padStart(3,"0")}

function init(){document.getElementById("chips").innerHTML=["All","Due","Urgent",...STATUSES].map(s=>`<button class="chip ${s==="All"?"active":""}" onclick="setStatus('${s}')">${s}</button>`).join("");document.getElementById("status").innerHTML=STATUSES.map(x=>`<option>${x}</option>`).join("");document.getElementById("reportMonth").value=currentMonthValue();renderAll();if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js?v=6").then(r=>r.update()).catch(()=>{})}}
function renderAll(){renderOrders();renderToday();renderAnalytics();renderTeam()}
function setStatus(s){selectedStatus=s;[...document.querySelectorAll(".chip")].forEach(b=>b.classList.toggle("active",b.textContent===s));renderOrders()}
function orderMatchesFilter(o){if(selectedStatus==="All")return true;if(selectedStatus==="Due")return orderDue(o)>0;if(selectedStatus==="Urgent")return o.priority==="Urgent"||o.priority==="Same Day";return o.status===selectedStatus}
function renderOrders(){const orders=getOrders(),q=document.getElementById("search").value.trim().toLowerCase();const filtered=orders.filter(orderMatchesFilter).filter(o=>!q||[o.orderNumber,o.customerName,o.phone,o.recipientName,o.recipientPhone,o.bouquetName,o.deliveryAddress].some(x=>(x||"").toLowerCase().includes(q))).sort((a,b)=>new Date(a.deliveryDate||0)-new Date(b.deliveryDate||0));document.getElementById("openCount").textContent=orders.filter(o=>o.status!=="Delivered").length;document.getElementById("todayCount").textContent=orders.filter(o=>o.status!=="Delivered"&&isToday(o.deliveryDate)).length;document.getElementById("dueTop").textContent="Rs. "+money(orders.reduce((s,o)=>s+orderDue(o),0));const list=document.getElementById("orderList");if(!filtered.length){list.innerHTML='<div class="empty">No orders found.<br>Tap + to add one.</div>';return}list.innerHTML=filtered.map(o=>{const due=orderDue(o),urgent=o.priority==="Urgent"||o.priority==="Same Day";return `<div class="order ${urgent?"urgent-order":""}" onclick="openDetail('${o.id}')"><div class="row"><h3>${esc(o.orderNumber)}</h3><div><span class="badge">${esc(o.status||"New")}</span>${urgent?` <span class="badge urgent">${esc(o.priority)}</span>`:""}</div></div><div class="customer">${esc(o.customerName||"")}${o.recipientName?` → ${esc(o.recipientName)}`:""}</div><div class="bouquet">${esc(o.bouquetName||"")}</div><div class="meta"><span>${formatDate(o.deliveryDate)}</span><span>${due>0?`Due Rs. ${money(due)}`:"Paid"}</span></div></div>`}).join("")}

function openNew(){editingId=null;document.getElementById("formTitle").textContent="New Order";["customerName","phone","recipientName","recipientPhone","bouquetName","flowerDetails","cardMessage","deliveryAddress","amount","deliveryFee","advanceAmount","totalAmount","dueAmount","paymentStatus","flowerCost","wrappingCost","deliveryCost","otherCost","profitPreview","notes"].forEach(id=>document.getElementById(id).value="");document.getElementById("orderNumber").value=nextOrderNumber();document.getElementById("orderDate").value=localDateInput();document.getElementById("deliveryDate").value=toLocalInput(new Date());document.getElementById("occasion").value="Birthday";document.getElementById("leadSource").value="Meta Ads";document.getElementById("priority").value="Normal";document.getElementById("status").value="New";document.getElementById("prepStatus").value="Pending";document.getElementById("designStatus").value="Pending";document.getElementById("deliveryStatus").value="Pending";document.getElementById("advanceAmount").readOnly=false;document.getElementById("advanceLabel").textContent="Advance Paid (LKR)";syncPaymentFields();document.getElementById("orderModal").classList.add("show")}
function syncPaymentFields(){const total=n(document.getElementById("amount").value)+n(document.getElementById("deliveryFee").value);const adv=n(document.getElementById("advanceAmount").value);const due=Math.max(total-adv,0);const cost=n(document.getElementById("flowerCost").value)+n(document.getElementById("wrappingCost").value)+n(document.getElementById("deliveryCost").value)+n(document.getElementById("otherCost").value);document.getElementById("totalAmount").value=total;document.getElementById("dueAmount").value=due;document.getElementById("paymentStatus").value=total>0&&due<=0?"Paid":adv>0?"Deposit Paid":"Unpaid";document.getElementById("profitPreview").value=total-cost}
function formData(){const orders=getOrders(),old=editingId?orders.find(o=>o.id===editingId):null;let payments=old?orderPayments(old):[];if(!old){const adv=n(document.getElementById("advanceAmount").value);if(adv>0)payments=[{id:crypto.randomUUID(),amount:adv,date:new Date().toISOString(),note:"Advance"}]}return {id:editingId||crypto.randomUUID(),orderNumber:document.getElementById("orderNumber").value.trim(),orderDate:document.getElementById("orderDate").value||localDateInput(),customerName:document.getElementById("customerName").value.trim(),phone:document.getElementById("phone").value.trim(),recipientName:document.getElementById("recipientName").value.trim(),recipientPhone:document.getElementById("recipientPhone").value.trim(),occasion:document.getElementById("occasion").value,leadSource:document.getElementById("leadSource").value,priority:document.getElementById("priority").value,bouquetName:document.getElementById("bouquetName").value.trim(),flowerDetails:document.getElementById("flowerDetails").value.trim(),cardMessage:document.getElementById("cardMessage").value.trim(),deliveryDate:document.getElementById("deliveryDate").value,deliveryAddress:document.getElementById("deliveryAddress").value.trim(),deliveryFee:n(document.getElementById("deliveryFee").value),amount:n(document.getElementById("amount").value),payments,flowerCost:n(document.getElementById("flowerCost").value),wrappingCost:n(document.getElementById("wrappingCost").value),deliveryCost:n(document.getElementById("deliveryCost").value),otherCost:n(document.getElementById("otherCost").value),status:document.getElementById("status").value,prepStatus:document.getElementById("prepStatus").value,designStatus:document.getElementById("designStatus").value,deliveryStatus:document.getElementById("deliveryStatus").value,notes:document.getElementById("notes").value.trim(),createdAt:old?.createdAt||new Date().toISOString()}}
function saveOrder(){const name=document.getElementById("customerName").value.trim(),bouquet=document.getElementById("bouquetName").value.trim();if(!name||!bouquet){alert("Please enter buyer name and bouquet name.");return}let orders=getOrders(),obj=formData();if(editingId)orders=orders.map(o=>o.id===editingId?obj:o);else orders.push(obj);setOrders(orders);closeModal();renderAll()}
function editCurrent(){const o=getOrders().find(x=>x.id===currentId);if(!o)return;closeDetail();editingId=o.id;document.getElementById("formTitle").textContent="Edit Order";const vals={orderNumber:o.orderNumber,orderDate:o.orderDate||(o.createdAt||"").slice(0,10),customerName:o.customerName,phone:o.phone,recipientName:o.recipientName||"",recipientPhone:o.recipientPhone||"",occasion:o.occasion||"Other",leadSource:o.leadSource||"Other",priority:o.priority||"Normal",bouquetName:o.bouquetName,flowerDetails:o.flowerDetails,cardMessage:o.cardMessage,deliveryDate:o.deliveryDate,deliveryAddress:o.deliveryAddress,deliveryFee:orderDeliveryFee(o),amount:orderBouquetValue(o),advanceAmount:orderPaid(o),flowerCost:n(o.flowerCost),wrappingCost:n(o.wrappingCost),deliveryCost:n(o.deliveryCost),otherCost:n(o.otherCost),status:o.status||"New",prepStatus:o.prepStatus||"Pending",designStatus:o.designStatus||"Pending",deliveryStatus:o.deliveryStatus||"Pending",notes:o.notes||""};Object.entries(vals).forEach(([k,v])=>{const el=document.getElementById(k);if(el)el.value=v??""});document.getElementById("advanceAmount").readOnly=true;document.getElementById("advanceLabel").textContent="Total Paid — use Add Payment in order view";syncPaymentFields();document.getElementById("orderModal").classList.add("show")}
function closeModal(){document.getElementById("orderModal").classList.remove("show")}
function backdropClose(e){if(e.target.id==="orderModal")closeModal()}

function openDetail(id){currentId=id;const o=getOrders().find(x=>x.id===id);if(!o)return;document.getElementById("detailTitle").textContent=o.orderNumber||"Order";const parts=[["Buyer",o.customerName],["Buyer Phone",o.phone],["Recipient",o.recipientName],["Recipient Phone",o.recipientPhone],["Occasion",o.occasion],["Lead Source",o.leadSource],["Priority",o.priority],["Bouquet",o.bouquetName],["Flowers / Colours",o.flowerDetails],["Card Message",o.cardMessage],["Delivery",formatDate(o.deliveryDate)],["Address",o.deliveryAddress],["Bouquet Value","Rs. "+money(orderBouquetValue(o))],["Delivery Fee","Rs. "+money(orderDeliveryFee(o))],["Total","Rs. "+money(orderTotal(o))],["Paid","Rs. "+money(orderPaid(o))],["Due","Rs. "+money(orderDue(o))],["Payment",paymentStatus(o)],["Costs","Rs. "+money(orderCosts(o))],["Gross Profit","Rs. "+money(orderProfit(o))],["Overall Status",o.status],["Pasidu — Prep",o.prepStatus||"Pending"],["Nangi — Bouquet",o.designStatus||"Pending"],["Pasidu — Delivery",o.deliveryStatus||"Pending"],["Notes",o.notes]].filter(x=>x[1]!==undefined&&x[1]!==null&&x[1]!=="");document.getElementById("detailBody").innerHTML=parts.map(([a,b])=>`<div class="detail-card"><div class="detail-label">${esc(a)}</div><div class="detail-value">${esc(b)}</div></div>`).join("");renderPaymentHistory(o);const buyerMsg=`Hi ${o.customerName||""}, your Serendib Petals order ${o.orderNumber||""} is confirmed. ${orderDue(o)>0?`Balance due: Rs. ${money(orderDue(o))}.`:"Payment is complete."}`;const recipientMsg=`Hi ${o.recipientName||""}, your Serendib Petals order is ${o.deliveryStatus==="Out for Delivery"?"out for delivery":"being prepared"}.`;document.getElementById("whatsappActions").innerHTML=(o.phone?`<a class="actionbtn wa" target="_blank" href="${waLink(o.phone,buyerMsg)}">WhatsApp Buyer</a>`:"")+(o.recipientPhone?`<a class="actionbtn secondary" target="_blank" href="${waLink(o.recipientPhone,recipientMsg)}">WhatsApp Recipient</a>`:"");document.getElementById("detailModal").classList.add("show")}
function renderPaymentHistory(o){const ps=orderPayments(o);document.getElementById("paymentHistory").innerHTML=ps.length?ps.map(p=>`<div class="payment-row"><div><b>Rs. ${money(p.amount)}</b><small>${new Date(p.date).toLocaleString()}${p.note?` • ${esc(p.note)}`:""}</small></div><button onclick="removePayment('${p.id}')">×</button></div>`).join(""):'<p class="mini">No payments recorded yet.</p>'}
function addPayment(){const amount=n(document.getElementById("newPaymentAmount").value),note=document.getElementById("newPaymentNote").value.trim();if(amount<=0){alert("Enter a payment amount.");return}let orders=getOrders(),o=orders.find(x=>x.id===currentId);if(!o)return;const due=orderDue(o);if(due<=0){alert("This order is already fully paid.");return}const pay=Math.min(amount,due),payments=orderPayments(o).filter(p=>!String(p.id).startsWith("legacy-"));if(!Array.isArray(o.payments)&&orderPaid(o)>0)payments.push({id:crypto.randomUUID(),amount:orderPaid(o),date:o.createdAt||new Date().toISOString(),note:"Previous payment"});payments.push({id:crypto.randomUUID(),amount:pay,date:new Date().toISOString(),note});o={...o,payments,advanceAmount:undefined,paymentStatus:undefined};orders=orders.map(x=>x.id===o.id?o:x);setOrders(orders);document.getElementById("newPaymentAmount").value="";document.getElementById("newPaymentNote").value="";renderAll();openDetail(o.id)}
function removePayment(pid){if(!confirm("Remove this payment record?"))return;let orders=getOrders(),o=orders.find(x=>x.id===currentId);if(!o)return;o={...o,payments:orderPayments(o).filter(p=>p.id!==pid)};orders=orders.map(x=>x.id===o.id?o:x);setOrders(orders);renderAll();openDetail(o.id)}
function deleteCurrent(){if(!confirm("Delete this order?"))return;setOrders(getOrders().filter(o=>o.id!==currentId));closeDetail();renderAll()}
function closeDetail(){document.getElementById("detailModal").classList.remove("show")}
function backdropCloseDetail(e){if(e.target.id==="detailModal")closeDetail()}

function renderToday(){const orders=getOrders(),today=orders.filter(o=>o.status!=="Delivered"&&isToday(o.deliveryDate)).sort((a,b)=>new Date(a.deliveryDate)-new Date(b.deliveryDate));document.getElementById("todayDeliveries").innerHTML=today.length?today.map(o=>miniOrder(o)).join(""):'<p class="mini">No deliveries today.</p>';const due=orders.filter(o=>orderDue(o)>0).sort((a,b)=>orderDue(b)-orderDue(a));document.getElementById("dueList").innerHTML=due.length?due.map(o=>`<div class="mini-order" onclick="openDetail('${o.id}')"><b>${esc(o.orderNumber)} — ${esc(o.customerName)}</b><span>Due Rs. ${money(orderDue(o))}</span></div>`).join(""):'<p class="mini">No outstanding balances.</p>';const prep=orders.filter(o=>o.status!=="Delivered"&&(o.prepStatus||"Pending")!=="Done").length;const design=orders.filter(o=>o.status!=="Delivered"&&(o.designStatus||"Pending")!=="Done").length;const delivery=orders.filter(o=>o.status!=="Delivered"&&(o.deliveryStatus||"Pending")!=="Delivered").length;document.getElementById("taskList").innerHTML=`<div class="task-grid"><div><b>${prep}</b><span>Pasidu Prep</span></div><div><b>${design}</b><span>Nangi Bouquets</span></div><div><b>${delivery}</b><span>Pasidu Delivery</span></div></div>`}
function miniOrder(o){return `<div class="mini-order" onclick="openDetail('${o.id}')"><b>${esc(o.orderNumber)} — ${esc(o.recipientName||o.customerName)}</b><span>${formatDate(o.deliveryDate)} • ${esc(o.deliveryAddress||"")}</span></div>`}
function renderTeam(){const orders=getOrders().filter(o=>o.status!=="Delivered");document.getElementById("eluwaTasks").textContent=`${orders.length} open customer orders`;document.getElementById("pasiduTasks").textContent=`${orders.filter(o=>(o.prepStatus||"Pending")!=="Done").length} prep • ${orders.filter(o=>(o.deliveryStatus||"Pending")!=="Delivered").length} delivery`;document.getElementById("nangiTasks").textContent=`${orders.filter(o=>(o.designStatus||"Pending")!=="Done").length} bouquets pending`}

function selectedReportOrders(){const all=getOrders(),month=document.getElementById("reportMonth")?.value||"",basis=document.getElementById("reportBasis")?.value||"delivery";if(reportMode==="all"||!month)return all;return all.filter(o=>{const v=basis==="order"?(o.orderDate||(o.createdAt||"").slice(0,10)):(o.deliveryDate||"");return String(v).slice(0,7)===month})}
function renderAnalytics(){const month=document.getElementById("reportMonth");if(month&&month.value)reportMode="month";const orders=selectedReportOrders(),sales=orders.reduce((s,o)=>s+orderTotal(o),0),collected=orders.reduce((s,o)=>s+orderPaid(o),0),due=orders.reduce((s,o)=>s+orderDue(o),0),profit=orders.reduce((s,o)=>s+orderProfit(o),0),del=orders.filter(o=>o.status==="Delivered"||o.deliveryStatus==="Delivered").length;const period=reportMode==="all"?"All Time":monthLabel(month?.value||"");document.getElementById("periodLabel").textContent=period;document.getElementById("revStat").textContent="Rs. "+money(sales);document.getElementById("collectedStat").textContent="Rs. "+money(collected);document.getElementById("dueStat").textContent="Rs. "+money(due);document.getElementById("profitStat").textContent="Rs. "+money(profit);document.getElementById("ordersStat").textContent=orders.length;document.getElementById("deliveryStat").textContent=del;document.getElementById("reportDate").textContent=`Period: ${period} • Generated: ${new Date().toLocaleString()}`;document.getElementById("reportSummary").textContent=`Orders ${orders.length} | Sales Rs. ${money(sales)} | Collected Rs. ${money(collected)} | Due Rs. ${money(due)} | Gross profit Rs. ${money(profit)}`;const sources={};orders.forEach(o=>{const s=o.leadSource||"Unknown";sources[s]=(sources[s]||0)+1});document.getElementById("sourceBreakdown").innerHTML=`<h4>Lead Sources</h4>${Object.entries(sources).sort((a,b)=>b[1]-a[1]).map(([s,c])=>`<div class="source-row"><span>${esc(s)}</span><b>${c}</b></div>`).join("")||"<p>No data.</p>"}`;document.getElementById("reportTable").innerHTML=orders.length?`<div class="tablewrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Sales</th><th>Paid</th><th>Due</th><th>Profit</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${esc(o.orderNumber)}</td><td>${esc(o.customerName)}</td><td>Rs. ${money(orderTotal(o))}</td><td>Rs. ${money(orderPaid(o))}</td><td>Rs. ${money(orderDue(o))}</td><td>Rs. ${money(orderProfit(o))}</td></tr>`).join("")}</tbody></table></div>`:"<p>No orders for this period.</p>"}
function showAllTimeReport(){reportMode="all";document.getElementById("reportMonth").value="";renderAnalytics()}
function showPage(page){["orders","today","analytics","team"].forEach(x=>{document.getElementById(x+"Page").classList.toggle("hidden",x!==page);document.getElementById("tab"+x.charAt(0).toUpperCase()+x.slice(1)).classList.toggle("active",x===page)});if(page==="today")renderToday();if(page==="analytics")renderAnalytics();if(page==="team")renderTeam()}

function csvEscape(v){v=String(v??"");return/[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function exportCSV(){const orders=selectedReportOrders();const headers=["Order","Order Date","Buyer","Buyer Phone","Recipient","Recipient Phone","Occasion","Lead Source","Priority","Bouquet","Delivery Date","Address","Bouquet Value","Delivery Fee","Total","Paid","Due","Flower Cost","Wrapping Cost","Delivery Cost","Other Cost","Gross Profit","Status","Prep","Design","Delivery","Notes"];const rows=orders.map(o=>[o.orderNumber,o.orderDate,o.customerName,o.phone,o.recipientName,o.recipientPhone,o.occasion,o.leadSource,o.priority,o.bouquetName,formatDate(o.deliveryDate),o.deliveryAddress,orderBouquetValue(o),orderDeliveryFee(o),orderTotal(o),orderPaid(o),orderDue(o),n(o.flowerCost),n(o.wrappingCost),n(o.deliveryCost),n(o.otherCost),orderProfit(o),o.status,o.prepStatus,o.designStatus,o.deliveryStatus,o.notes]);const csv=[headers,...rows].map(r=>r.map(csvEscape).join(",")).join("\n");downloadBlob(csv,`serendib-orders-${new Date().toISOString().slice(0,10)}.csv`,"text/csv;charset=utf-8")}
function backupJSON(){downloadBlob(JSON.stringify({version:6,exportedAt:new Date().toISOString(),orders:getOrders()},null,2),"serendib-orders-backup-"+new Date().toISOString().slice(0,10)+".json","application/json")}
function restoreBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result),orders=Array.isArray(p)?p:p.orders;if(!Array.isArray(orders))throw 0;if(!confirm(`Restore ${orders.length} orders?`))return;setOrders(orders);renderAll();alert("Backup restored.")}catch{alert("Invalid backup file.")}finally{e.target.value=""}};r.readAsText(f)}
function resetAllData(){if(!confirm("Delete ALL orders on this device?"))return;const c=prompt("Type RESET to continue.");if(c!=="RESET")return;setOrders([]);renderAll();alert("All orders reset.")}
function downloadBlob(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function shareSummary(){const orders=selectedReportOrders(),sales=orders.reduce((s,o)=>s+orderTotal(o),0),due=orders.reduce((s,o)=>s+orderDue(o),0),profit=orders.reduce((s,o)=>s+orderProfit(o),0);const text=`Serendib Petals\nOrders: ${orders.length}\nSales: Rs. ${money(sales)}\nDue: Rs. ${money(due)}\nGross profit: Rs. ${money(profit)}`;if(navigator.share){try{await navigator.share({title:"Serendib Petals Report",text})}catch{}}else{navigator.clipboard?.writeText(text);alert("Summary copied.")}}

init();