/* Serendib Petals v12 — cloud expenses ledger */
(function(){
  if(window.__SP_EXPENSES_V12__)return;window.__SP_EXPENSES_V12__=true;
  const CACHE='serendib_expenses_cache_v12';
  const ORDER_CACHE='serendib_orders_preview';
  const CATS=['Marketing & Ads','Delivery & Fuel','Rent & Utilities','Software & Subscriptions','Equipment','Staff & Wages','Office & Admin','Flowers / Stock (General)','Wrapping / Packaging (General)','Other'];
  let rows=[],editing=null,allTime=false,channel=null,ready=false;
  const n=v=>Math.max(Number(v||0),0);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=v=>Number(v||0).toLocaleString();
  const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
  const monthKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
  const orders=()=>{try{return JSON.parse(localStorage.getItem(ORDER_CACHE)||'[]')||[]}catch{return[]}};
  const client=()=>window.SerendibCloud?.client||null;
  const member=()=>window.SerendibCloud?.member||null;
  const cacheRead=()=>{try{return JSON.parse(localStorage.getItem(CACHE)||'[]')||[]}catch{return[]}};
  const cacheWrite=v=>{rows=v||[];localStorage.setItem(CACHE,JSON.stringify(rows))};
  const orderGross=o=>n(o.amount)+n(o.deliveryFee)-n(o.flowerCost)-n(o.wrappingCost)-n(o.deliveryCost)-n(o.otherCost);
  const selectedMonth=()=>document.getElementById('spExpenseMonth')?.value||monthKey();
  const periodRows=()=>{const r=rows.length?rows:cacheRead();return allTime?r:r.filter(x=>String(x.expense_date||'').slice(0,7)===selectedMonth())};
  const periodOrders=()=>allTime?orders():orders().filter(o=>String(o.orderDate||(o.createdAt||'')).slice(0,7)===selectedMonth());

  function shell(){return `<div class="sp-exp-shell">
    <div class="sp-exp-top"><div><span class="sp-exp-kicker">FINANCE CONTROL</span><h2>Expenses & Operating Profit</h2><p>Track business expenses that are not already entered inside an individual order.</p></div><div class="sp-exp-top-actions"><button data-exp-export>Export CSV</button><button class="primary" data-exp-add>+ Add Expense</button></div></div>
    <div class="sp-exp-warning"><b>Avoid double-counting:</b> flower, wrapping and delivery costs already entered inside an order should not be entered here again. Use this ledger for ads, fuel, subscriptions, salaries, rent and other general spending.</div>
    <div class="sp-exp-filters"><label><span>Month</span><input type="month" id="spExpenseMonth" value="${monthKey()}"></label><button class="active" data-exp-this>This Month</button><button data-exp-all>All Time</button></div>
    <div class="sp-exp-kpis"><article><span>Expenses</span><strong id="spExpTotal">Rs. 0</strong><small id="spExpCount">0 entries</small></article><article><span>Order gross profit</span><strong id="spExpGross">Rs. 0</strong><small>Before general expenses</small></article><article class="profit"><span>Operating profit</span><strong id="spExpOperating">Rs. 0</strong><small>Gross profit − general expenses</small></article><article><span>Today</span><strong id="spExpToday">Rs. 0</strong><small>Business spending today</small></article></div>
    <div class="sp-exp-grid"><section class="sp-exp-panel"><div class="sp-exp-head"><div><span>CATEGORIES</span><h3>Where the money is going</h3></div></div><div id="spExpCats" class="sp-exp-cats"></div></section><section class="sp-exp-panel ledger"><div class="sp-exp-head"><div><span>LEDGER</span><h3>Expense history</h3></div><small id="spExpPeriod"></small></div><div id="spExpList" class="sp-exp-list"></div></section></div>
  </div>`}

  function modal(){return `<div class="sp-exp-modal" id="spExpModal"><div class="sp-exp-dialog"><div class="sp-exp-dialog-head"><div><span>BUSINESS EXPENSE</span><h3 id="spExpModalTitle">Add Expense</h3></div><button data-exp-close>×</button></div><div class="sp-exp-form"><div class="sp-exp-2"><label><span>Date</span><input type="date" id="spExpDate"></label><label><span>Amount (LKR)</span><input type="number" min="0" step="0.01" id="spExpAmount" inputmode="decimal"></label></div><label><span>Category</span><select id="spExpCategory">${CATS.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label><span>Description</span><input id="spExpDescription" placeholder="e.g. Meta Ads September campaign"></label><div class="sp-exp-2"><label><span>Vendor / Payee</span><input id="spExpVendor" placeholder="Optional"></label><label><span>Payment method</span><select id="spExpMethod"><option>Bank Transfer</option><option>Cash</option><option>Card</option><option>Online</option><option>Other</option></select></label></div><label><span>Notes</span><textarea id="spExpNotes" placeholder="Optional internal note"></textarea></label></div><div class="sp-exp-actions"><button class="secondary" data-exp-close>Cancel</button><button class="primary" data-exp-save>Save Expense</button></div></div></div>`}

  function ensureModal(){if(document.getElementById('spExpModal'))return;const h=document.createElement('div');h.innerHTML=modal();document.body.appendChild(h.firstElementChild);document.querySelectorAll('[data-exp-close]').forEach(b=>b.addEventListener('click',closeModal));document.querySelector('[data-exp-save]')?.addEventListener('click',save);document.getElementById('spExpModal')?.addEventListener('click',e=>{if(e.target.id==='spExpModal')closeModal()})}
  function openModal(id=null){ensureModal();editing=id;const r=id?rows.find(x=>x.id===id):null;document.getElementById('spExpModalTitle').textContent=r?'Edit Expense':'Add Expense';document.getElementById('spExpDate').value=r?.expense_date||today();document.getElementById('spExpAmount').value=r?.amount||'';document.getElementById('spExpCategory').value=r?.category||CATS[0];document.getElementById('spExpDescription').value=r?.description||'';document.getElementById('spExpVendor').value=r?.vendor||'';document.getElementById('spExpMethod').value=r?.payment_method||'Bank Transfer';document.getElementById('spExpNotes').value=r?.notes||'';document.getElementById('spExpModal').classList.add('show')}
  function closeModal(){document.getElementById('spExpModal')?.classList.remove('show');editing=null}

  async function save(){const c=client();if(!c||!window.SerendibCloud?.connected){alert('Cloud connection is not ready yet.');return}const amount=n(document.getElementById('spExpAmount')?.value),description=document.getElementById('spExpDescription')?.value.trim();if(amount<=0||!description){alert('Enter the expense amount and description.');return}const m=member();const payload={expense_date:document.getElementById('spExpDate')?.value||today(),category:document.getElementById('spExpCategory')?.value||'Other',description,amount,vendor:document.getElementById('spExpVendor')?.value.trim()||null,payment_method:document.getElementById('spExpMethod')?.value||null,notes:document.getElementById('spExpNotes')?.value.trim()||null,updated_by:m?.user_id||null};let res;if(editing)res=await c.from('expenses').update(payload).eq('id',editing);else{payload.created_by=m?.user_id||null;res=await c.from('expenses').insert(payload)}if(res.error){alert('Could not save expense: '+res.error.message);return}closeModal();await load(true)}
  async function remove(id){if(!confirm('Delete this expense record?'))return;const c=client();if(!c)return;const {error}=await c.from('expenses').delete().eq('id',id);if(error){alert('Could not delete expense: '+error.message);return}await load(true)}
  async function load(silent=false){const c=client();if(!c||!window.SerendibCloud?.connected){rows=cacheRead();render();return}const {data,error}=await c.from('expenses').select('*').order('expense_date',{ascending:false}).order('created_at',{ascending:false});if(error){if(!silent)console.warn(error.message);rows=cacheRead();render();return}cacheWrite(data||[]);render()}
  function subscribe(){const c=client();if(!c||channel)return;channel=c.channel('serendib-expenses-'+Math.random().toString(36).slice(2)).on('postgres_changes',{event:'*',schema:'public',table:'expenses'},()=>load(true)).subscribe()}
  function ensureCloud(){if(ready)return;if(window.SerendibCloud?.connected&&client()){ready=true;load(true);subscribe();return}setTimeout(ensureCloud,500)}

  function render(){const t=document.getElementById('spExpTotal');if(!t)return;const r=periodRows(),expense=r.reduce((s,x)=>s+n(x.amount),0),po=periodOrders(),gross=po.reduce((s,o)=>s+orderGross(o),0),operating=gross-expense,day=rows.filter(x=>x.expense_date===today()).reduce((s,x)=>s+n(x.amount),0);t.textContent='Rs. '+money(expense);document.getElementById('spExpCount').textContent=`${r.length} entr${r.length===1?'y':'ies'}`;document.getElementById('spExpGross').textContent='Rs. '+money(gross);const op=document.getElementById('spExpOperating');op.textContent=(operating<0?'- Rs. ':'Rs. ')+money(Math.abs(operating));op.classList.toggle('negative',operating<0);document.getElementById('spExpToday').textContent='Rs. '+money(day);const pl=document.getElementById('spExpPeriod');if(pl)pl.textContent=allTime?'All Time':new Date(selectedMonth()+'-01T00:00:00').toLocaleDateString([],{month:'long',year:'numeric'});
    const by={};r.forEach(x=>by[x.category||'Other']=(by[x.category||'Other']||0)+n(x.amount));const cats=Object.entries(by).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...cats.map(x=>x[1]));const cb=document.getElementById('spExpCats');if(cb)cb.innerHTML=cats.length?cats.map(([k,v])=>`<div class="sp-exp-cat"><div><span>${esc(k)}</span><b>Rs. ${money(v)}</b></div><div class="sp-exp-bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):'<div class="sp-exp-empty">No expenses in this period yet.</div>';
    const box=document.getElementById('spExpList');if(box)box.innerHTML=r.length?r.map(x=>`<div class="sp-exp-row"><div class="sp-exp-date"><b>${esc(new Date(x.expense_date+'T00:00:00').toLocaleDateString([],{month:'short',day:'numeric'}))}</b><span>${esc(x.payment_method||'')}</span></div><div class="sp-exp-main"><strong>${esc(x.description)}</strong><small>${esc(x.category||'Other')}${x.vendor?` • ${esc(x.vendor)}`:''}${x.notes?` • ${esc(x.notes)}`:''}</small></div><div class="sp-exp-amount">Rs. ${money(x.amount)}</div><div class="sp-exp-row-actions"><button data-exp-edit="${esc(x.id)}">Edit</button><button class="danger" data-exp-delete="${esc(x.id)}">Delete</button></div></div>`).join(''):'<div class="sp-exp-empty">No expense records found.</div>';box?.querySelectorAll('[data-exp-edit]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.expEdit)));box?.querySelectorAll('[data-exp-delete]').forEach(b=>b.addEventListener('click',()=>remove(b.dataset.expDelete)))}
  function exportCsv(){const r=periodRows();if(!r.length){alert('No expenses in this period.');return}const q=v=>{v=String(v??'');return/[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v};const data=[['Date','Category','Description','Amount','Vendor','Payment Method','Notes'],...r.map(x=>[x.expense_date,x.category,x.description,x.amount,x.vendor||'',x.payment_method||'',x.notes||''])].map(a=>a.map(q).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download=`serendib-expenses-${allTime?'all-time':selectedMonth()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

  function bind(root=document){root.querySelectorAll('[data-exp-add]').forEach(b=>{if(b.dataset.b)return;b.dataset.b='1';b.addEventListener('click',()=>openModal())});root.querySelectorAll('[data-exp-export]').forEach(b=>{if(b.dataset.b)return;b.dataset.b='1';b.addEventListener('click',exportCsv)});root.querySelectorAll('[data-exp-this]').forEach(b=>{if(b.dataset.b)return;b.dataset.b='1';b.addEventListener('click',()=>{allTime=false;const m=document.getElementById('spExpenseMonth');if(m)m.value=monthKey();root.querySelectorAll('.sp-exp-filters button').forEach(x=>x.classList.toggle('active',x===b));render()})});root.querySelectorAll('[data-exp-all]').forEach(b=>{if(b.dataset.b)return;b.dataset.b='1';b.addEventListener('click',()=>{allTime=true;root.querySelectorAll('.sp-exp-filters button').forEach(x=>x.classList.toggle('active',x===b));render()})});const m=root.querySelector('#spExpenseMonth');if(m&&!m.dataset.b){m.dataset.b='1';m.addEventListener('change',()=>{allTime=false;root.querySelectorAll('.sp-exp-filters button').forEach(x=>x.classList.toggle('active',x.hasAttribute('data-exp-this')));render()})}}

  function setupDesktop(){if(!document.querySelector('.desktop-app')||!document.querySelector('.nav'))return false;const nav=document.querySelector('.nav');if(!nav.querySelector('[data-view="expenses"]')){const b=document.createElement('button');b.className='nav-item';b.dataset.view='expenses';b.innerHTML='<span>◈</span> Expenses';const r=nav.querySelector('[data-view="analytics"]');r?.after(b);b.onclick=()=>window.switchView('expenses',b)}const work=document.querySelector('.workspace');if(work&&!document.getElementById('expensesView')){const s=document.createElement('section');s.id='expensesView';s.className='sp-exp-view hidden';s.innerHTML=shell();work.appendChild(s);bind(s)}if(typeof window.switchView==='function'&&!window.switchView.__exp12){const old=window.switchView;const wrap=function(view,button){const exp=document.getElementById('expensesView');if(view==='expenses'){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view==='expenses'));document.getElementById('dashboardView')?.classList.add('hidden');document.getElementById('operationsView')?.classList.add('hidden');document.getElementById('calendarView')?.classList.add('hidden');exp?.classList.remove('hidden');render();return}exp?.classList.add('hidden');return old(view,button)};wrap.__exp12=true;window.switchView=wrap}render();ensureCloud();return true}
  function setupMobile(){const phone=document.querySelector('.phone'),tabs=document.querySelector('.tabs');if(!phone||!tabs)return false;if(!document.getElementById('expensesPage')){const s=document.createElement('section');s.id='expensesPage';s.className='hidden';s.innerHTML=`<div class="top"><div class="header"><div><h1>Expenses</h1><div class="subtitle">Business spending & operating profit</div></div><button class="plus" data-exp-add>+ Expense</button></div></div><div class="analytics sp-exp-mobile">${shell()}</div>`;phone.insertBefore(s,tabs);bind(s)}if(!document.getElementById('tabExpenses')){const b=document.createElement('button');b.className='tab';b.id='tabExpenses';b.textContent='Expenses';b.onclick=()=>window.showPage('expenses');document.getElementById('tabAnalytics')?.after(b)}if(typeof window.showPage==='function'&&!window.showPage.__exp12){const old=window.showPage;const wrap=function(page){const exp=document.getElementById('expensesPage');if(page==='expenses'){['orders','today','analytics','team'].forEach(x=>document.getElementById(x+'Page')?.classList.add('hidden'));document.getElementById('calendarPage')?.classList.add('hidden');exp?.classList.remove('hidden');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.id==='tabExpenses'));render();return}exp?.classList.add('hidden');document.getElementById('tabExpenses')?.classList.remove('active');return old(page)};wrap.__exp12=true;window.showPage=wrap}render();ensureCloud();return true}
  function init(){const d=setupDesktop(),m=setupMobile();if(!d&&!m){setTimeout(init,150);return}window.addEventListener('focus',()=>{render();ensureCloud()});window.addEventListener('storage',render)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80));else setTimeout(init,80);
})();