/* Serendib Petals v14 — archived orders + audit history */
(function(){
  if(window.SerendibHistory)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=v=>Number(v||0).toLocaleString();
  const client=()=>window.SerendibCloud?.client||null;
  let archived=[],logs=[],filter='all';
  function shell(){return `<div class="sp-hist-shell"><div class="sp-hist-top"><span>CONTROL & TRACEABILITY</span><h2>History & Audit Log</h2><p>Cancelled or archived orders stay preserved here, while activity logs show what changed in the cloud system.</p></div><div class="sp-hist-grid"><section class="sp-hist-panel"><div class="sp-hist-head"><h3>Cancelled / Archived Orders</h3><select class="sp-hist-filter" id="spHistFilter"><option value="all">All</option><option value="cancelled">Cancelled</option><option value="archived">Archived</option></select></div><div id="spArchivedList" class="sp-hist-list"></div></section><section class="sp-hist-panel"><div class="sp-hist-head"><h3>Latest Activity</h3><button type="button" data-hist-refresh>Refresh</button></div><div id="spAuditList"></div></section></div></div>`}
  function render(){const a=filter==='all'?archived:archived.filter(x=>x.action===filter);const ab=document.getElementById('spArchivedList');if(ab)ab.innerHTML=a.length?a.map(x=>{const s=x.snapshot||{};return `<div class="sp-hist-row"><span class="sp-hist-amount">${Number(x.refund_amount||0)>0?`Refund Rs. ${money(x.refund_amount)}`:''}</span><b>${esc(x.order_number||'Order')}</b><span class="sp-hist-tag">${esc(x.action)}</span><small>${esc(s.customerName||s.buyer_name||'Customer')} • ${esc(s.bouquetName||s.bouquet_name||'Bouquet')}<br>${esc(x.reason||'No reason recorded')} • ${new Date(x.archived_at).toLocaleString()}</small></div>`}).join(''):'<div class="sp-hist-empty">No cancelled or archived orders yet.</div>';const lb=document.getElementById('spAuditList');if(lb)lb.innerHTML=logs.length?logs.map(x=>`<div class="sp-audit-row"><time>${esc(new Date(x.created_at).toLocaleString())}</time><span>${esc(x.table_name)}</span><div><b>${esc(x.action)}</b><small>${esc(describe(x))}</small></div></div>`).join(''):'<div class="sp-hist-empty">No activity recorded yet.</div>'}
  function describe(x){const a=x.after_data||x.before_data||{};if(x.table_name==='orders')return `${a.order_number||'Order'} • ${a.buyer_name||''}`.trim();if(x.table_name==='payments')return `Payment ${a.amount?`Rs. ${money(a.amount)}`:''}`.trim();if(x.table_name==='expenses')return `${a.description||'Expense'} ${a.amount?`• Rs. ${money(a.amount)}`:''}`.trim();if(x.table_name==='inventory_items')return a.name||'Inventory item';if(x.table_name==='inventory_movements')return `${a.movement_type||'Movement'} ${a.qty_change||''}`.trim();if(x.table_name==='order_requirements')return `Requirement ${a.qty_required||''}`.trim();return x.record_id||''}
  async function load(){const c=client();if(!c||!window.SerendibCloud?.connected)return;const [a,l]=await Promise.all([c.from('archived_orders').select('*').order('archived_at',{ascending:false}).limit(100),c.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(150)]);if(a.error||l.error){console.warn(a.error?.message||l.error?.message);return}archived=a.data||[];logs=l.data||[];render()}
  function mount(container){if(!container)return;if(!container.dataset.histMounted){container.innerHTML=shell();container.dataset.histMounted='1';container.querySelector('#spHistFilter')?.addEventListener('change',e=>{filter=e.target.value;render()});container.querySelector('[data-hist-refresh]')?.addEventListener('click',load)}const wait=()=>{if(window.SerendibCloud?.connected)load();else setTimeout(wait,400)};wait()}
  window.SerendibHistory={mount,refresh:load};
})();