/* Serendib Petals v14 — inventory + upcoming requirements planner */
(function(){
  if(window.SerendibInventory)return;
  const ORDER_KEY='serendib_orders_preview';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const n=v=>Math.max(Number(v||0),0),money=v=>Number(v||0).toLocaleString();
  const client=()=>window.SerendibCloud?.client||null,member=()=>window.SerendibCloud?.member||null;
  const orders=()=>{try{return JSON.parse(localStorage.getItem(ORDER_KEY)||'[]')||[]}catch{return[]}};
  let items=[],reqs=[],channel=null,mode='item',editingItem=null;
  const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
  const plusDays=x=>{const d=new Date();d.setDate(d.getDate()+x);const o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
  const upcomingOrders=()=>orders().filter(o=>{const d=String(o.deliveryDate||'').slice(0,10);return d>=today()&&d<=plusDays(7)&&o.status!=='Delivered'&&o.deliveryStatus!=='Delivered'});
  const orderById=id=>orders().find(o=>o.id===id);
  const itemById=id=>items.find(i=>i.id===id);

  function shell(){return `<div class="sp-inv-shell"><div class="sp-inv-top"><div><span>STOCK & PROCUREMENT</span><h2>Inventory Planner</h2><p>Track stock and calculate what the next 7 days of confirmed deliveries need.</p></div><div class="sp-inv-actions"><button data-inv-req>+ Order Requirement</button><button class="primary" data-inv-item>+ Inventory Item</button></div></div><div class="sp-inv-kpis"><article><span>Active items</span><strong id="spInvItems">0</strong><small>Stock lines</small></article><article><span>Low stock</span><strong id="spInvLow">0</strong><small>At/below reorder level</small></article><article><span>Next 7 days</span><strong id="spInvReq">0</strong><small>Total required units</small></article><article><span>Shortages</span><strong id="spInvShort">0</strong><small>Items to buy</small></article></div><div class="sp-inv-grid"><section class="sp-inv-panel"><div class="sp-inv-head"><h3>Current stock</h3><small>Adjust through movements</small></div><div id="spInvStock" class="sp-inv-list"></div></section><section class="sp-inv-panel"><div class="sp-inv-head"><h3>7-day requirement plan</h3><small>From upcoming orders</small></div><div id="spInvPlanner"></div></section></div></div>`}
  function ensureModal(){if(document.getElementById('spInvModal'))return;const x=document.createElement('div');x.innerHTML='<div class="sp-inv-modal" id="spInvModal"><div class="sp-inv-dialog"><div class="sp-inv-dialog-head"><h3 id="spInvModalTitle">Inventory</h3><button type="button" data-inv-close>×</button></div><div class="sp-inv-form" id="spInvForm"></div><div class="sp-inv-form-actions"><button data-inv-close>Cancel</button><button class="primary" data-inv-save>Save</button></div></div></div>';document.body.appendChild(x.firstElementChild);document.querySelectorAll('[data-inv-close]').forEach(b=>b.addEventListener('click',closeModal));document.querySelector('[data-inv-save]')?.addEventListener('click',saveModal);document.getElementById('spInvModal')?.addEventListener('click',e=>{if(e.target.id==='spInvModal')closeModal()})}
  function openItem(id=null){ensureModal();mode='item';editingItem=id;const i=id?itemById(id):null;document.getElementById('spInvModalTitle').textContent=i?'Edit Inventory Item':'Add Inventory Item';document.getElementById('spInvForm').innerHTML=`<label><span>Item name</span><input id="spInvName" value="${esc(i?.name||'')}"></label><div class="sp-inv-2"><label><span>Category</span><select id="spInvCategory"><option>Flowers</option><option>Wrapping</option><option>Ribbon</option><option>Cards</option><option>Packaging</option><option>Other</option></select></label><label><span>Unit</span><input id="spInvUnit" value="${esc(i?.unit||'stems')}"></label></div><div class="sp-inv-2"><label><span>Reorder level</span><input type="number" min="0" id="spInvReorder" value="${n(i?.reorder_level)}"></label><label><span>Cost per unit</span><input type="number" min="0" step="0.01" id="spInvCost" value="${n(i?.cost_per_unit)}"></label></div>${i?'':`<label><span>Opening stock</span><input type="number" min="0" step="0.01" id="spInvOpening" value="0"></label>`}`;document.getElementById('spInvCategory').value=i?.category||'Flowers';document.getElementById('spInvModal').classList.add('show')}
  function openAdjust(id){ensureModal();mode='adjust';editingItem=id;const i=itemById(id);document.getElementById('spInvModalTitle').textContent='Adjust Stock — '+(i?.name||'Item');document.getElementById('spInvForm').innerHTML=`<div class="sp-inv-2"><label><span>Movement</span><select id="spInvMoveType"><option value="purchase">Purchase / Add</option><option value="used">Used</option><option value="waste">Waste</option><option value="return">Return</option><option value="adjustment">Adjustment</option></select></label><label><span>Quantity</span><input type="number" min="0.01" step="0.01" id="spInvQty"></label></div><label><span>Note</span><input id="spInvNote" placeholder="Supplier, correction, event…"></label>`;document.getElementById('spInvModal').classList.add('show')}
  function openReq(){ensureModal();mode='req';editingItem=null;const os=upcomingOrders();document.getElementById('spInvModalTitle').textContent='Add Order Requirement';document.getElementById('spInvForm').innerHTML=`<label><span>Upcoming order</span><select id="spInvOrder">${os.map(o=>`<option value="${esc(o.id)}">${esc(o.orderNumber||'Order')} • ${esc(o.customerName||'Customer')} • ${esc(String(o.deliveryDate||'').slice(0,10))}</option>`).join('')}</select></label><label><span>Inventory item</span><select id="spInvReqItem">${items.filter(i=>i.active).map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${n(i.on_hand)} ${esc(i.unit)})</option>`).join('')}</select></label><div class="sp-inv-2"><label><span>Quantity required</span><input type="number" min="0.01" step="0.01" id="spInvReqQty"></label><label><span>Note</span><input id="spInvReqNote" placeholder="e.g. red roses"></label></div>${!os.length?'<div class="sp-inv-empty">No upcoming orders in the next 7 days.</div>':''}`;document.getElementById('spInvModal').classList.add('show')}
  function closeModal(){document.getElementById('spInvModal')?.classList.remove('show')}
  async function saveModal(){const c=client();if(!c||!window.SerendibCloud?.connected){alert('Cloud connection is not ready.');return}const uid=member()?.user_id||null;try{if(mode==='item'){const name=document.getElementById('spInvName')?.value.trim();if(!name){alert('Enter item name.');return}const p={name,category:document.getElementById('spInvCategory').value,unit:document.getElementById('spInvUnit').value.trim()||'units',reorder_level:n(document.getElementById('spInvReorder').value),cost_per_unit:n(document.getElementById('spInvCost').value),updated_by:uid};if(editingItem){const {error}=await c.from('inventory_items').update(p).eq('id',editingItem);if(error)throw error}else{p.created_by=uid;const {data,error}=await c.from('inventory_items').insert(p).select('id').single();if(error)throw error;const opening=n(document.getElementById('spInvOpening')?.value);if(opening>0){const {error:mErr}=await c.from('inventory_movements').insert({item_id:data.id,qty_change:opening,movement_type:'adjustment',note:'Opening stock',created_by:uid});if(mErr)throw mErr}}}else if(mode==='adjust'){let qty=n(document.getElementById('spInvQty').value);if(qty<=0){alert('Enter quantity.');return}const type=document.getElementById('spInvMoveType').value;if(['used','waste'].includes(type))qty=-qty;const {error}=await c.from('inventory_movements').insert({item_id:editingItem,qty_change:qty,movement_type:type,note:document.getElementById('spInvNote').value.trim()||null,created_by:uid});if(error)throw error}else{const order_id=document.getElementById('spInvOrder')?.value,item_id=document.getElementById('spInvReqItem')?.value,qty=n(document.getElementById('spInvReqQty')?.value);if(!order_id||!item_id||qty<=0){alert('Choose order, item and quantity.');return}const {error}=await c.from('order_requirements').upsert({order_id,item_id,qty_required:qty,note:document.getElementById('spInvReqNote').value.trim()||null,created_by:uid},{onConflict:'order_id,item_id'});if(error)throw error}closeModal();await load()}catch(e){alert('Could not save inventory change: '+(e?.message||e))}}
  async function load(){const c=client();if(!c||!window.SerendibCloud?.connected)return;const [a,b]=await Promise.all([c.from('inventory_items').select('*').eq('active',true).order('name'),c.from('order_requirements').select('*')]);if(a.error||b.error){console.warn(a.error?.message||b.error?.message);return}items=a.data||[];reqs=b.data||[];render()}
  function render(){const low=items.filter(i=>n(i.on_hand)<=n(i.reorder_level));const ups=new Set(upcomingOrders().map(o=>o.id));const activeReq=reqs.filter(r=>ups.has(r.order_id));const by={};activeReq.forEach(r=>{by[r.item_id]=(by[r.item_id]||0)+n(r.qty_required)});const shortages=Object.entries(by).filter(([id,q])=>q>n(itemById(id)?.on_hand));document.getElementById('spInvItems').textContent=items.length;document.getElementById('spInvLow').textContent=low.length;document.getElementById('spInvReq').textContent=money(Object.values(by).reduce((s,v)=>s+v,0));document.getElementById('spInvShort').textContent=shortages.length;const stock=document.getElementById('spInvStock');if(stock)stock.innerHTML=items.length?items.map(i=>`<div class="sp-inv-row"><div><b>${esc(i.name)}</b><small>${esc(i.category)} • ${esc(i.unit)}</small></div><span class="${n(i.on_hand)<=n(i.reorder_level)?'sp-inv-low':'sp-inv-good'}">${money(i.on_hand)}</span><span>Reorder ${money(i.reorder_level)}</span><span>Rs. ${money(i.cost_per_unit)}</span><button data-inv-adjust="${esc(i.id)}">Adjust</button></div>`).join(''):'<div class="sp-inv-empty">No inventory items yet.</div>';stock?.querySelectorAll('[data-inv-adjust]').forEach(b=>b.addEventListener('click',()=>openAdjust(b.dataset.invAdjust)));const plan=document.getElementById('spInvPlanner');const rows=Object.entries(by).sort((a,b)=>b[1]-a[1]);if(plan)plan.innerHTML=rows.length?rows.map(([id,q])=>{const i=itemById(id),short=Math.max(q-n(i?.on_hand),0);return `<div class="sp-inv-req"><div><b>${esc(i?.name||'Item')}</b><small>${esc(i?.unit||'units')} needed across next 7 days</small></div><span>Need ${money(q)}</span><span>Have ${money(i?.on_hand)}</span><span class="${short>0?'sp-inv-short':'sp-inv-good'}">${short>0?'Buy '+money(short):'Covered'}</span></div>`}).join(''):'<div class="sp-inv-empty">Add requirements to upcoming orders to build the purchase plan.</div>'}
  function subscribe(){const c=client();if(!c||channel)return;channel=c.channel('sp-inventory-v14').on('postgres_changes',{event:'*',schema:'public',table:'inventory_items'},load).on('postgres_changes',{event:'*',schema:'public',table:'inventory_movements'},load).on('postgres_changes',{event:'*',schema:'public',table:'order_requirements'},load).subscribe()}
  function mount(container){if(!container)return;if(!container.dataset.invMounted){container.innerHTML=shell();container.dataset.invMounted='1';container.querySelector('[data-inv-item]')?.addEventListener('click',()=>openItem());container.querySelector('[data-inv-req]')?.addEventListener('click',openReq)}const wait=()=>{if(window.SerendibCloud?.connected&&client()){load();subscribe()}else setTimeout(wait,400)};wait()}
  window.SerendibInventory={mount,refresh:load};
})();